<?xml version="1.0" encoding="utf-8"?><Database Name="AdminAttendance" Class="dbTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-14VJT84\SQLEXPRESS;Initial Catalog=AdminAttendance;Integrated Security=True" SettingsObjectName="TEST12.Properties.Settings" SettingsPropertyName="AdminAttendanceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblLogin" Member="tblLogins">
    <Type Name="tblLogin">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>